version: "3"
services:

  tvheadend:
    build: .
    restart: unless-stopped
    volumes:
      - /srv/tvh/config:/config
      - /srv/tvh/recordings:/recordings
    container_name: tvheadend
    network_mode: "host"
